### ISSUE TITLE
Shooting the reworked dice on the ground makes it fire super fast... Not sure if it's a conflict with another mod.

### ISSUE THREAD

**Issue by mypingishuge** [pseudopulse/StormTweaks#7]
Hitting the ground makes the cleaver instantly return and you can instantly fire another. I tried disabling all other mods that could be causing this and it still happens. Pls fix x3

**Comment by DamageMaximo** [comment]
not happening to me

**Comment by mypingishuge** [comment]
Here's a video showing the issue: https://imgur.com/a/PUkHMSl

**Comment by mypingishuge** [comment]
It was conflict with BetterChefPrimary, fixed now!
